version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:5.0
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/5.0#configuration for more options
            PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
            NOMINATIM_PASSWORD: very_secure_password
        volumes:
            - nominatim-data:/var/lib/postgresql/16/main
        shm_size: 1gb

volumes:
    nominatim-data:
